"""Execution telemetry models for tracking token spend, latency, and FinOps costs."""

from pydantic import BaseModel, ConfigDict, Field


class SpanMetric(BaseModel):
    """Timing and metadata for a single execution span (e.g. LLM inference vs MCP tool)."""

    name: str = Field(..., description="Name of the trace span")
    duration_seconds: float = Field(..., description="Duration of this specific step in seconds")
    attributes: dict[str, str | int | float | bool] = Field(
        default_factory=dict, description="Span semantic attributes"
    )


class ExecutionTelemetry(BaseModel):
    """Execution telemetry capturing runtime, token consumption, and estimated cost."""

    model_config = ConfigDict(populate_by_name=True)

    prompt_tokens: int = Field(default=0, description="Total input tokens sent to LLM")
    candidates_tokens: int = Field(default=0, description="Total output tokens generated by LLM")
    total_tokens: int = Field(default=0, description="Cumulative token count")
    latency_seconds: float = Field(default=0.0, description="Wall-clock execution duration in seconds")
    llm_latency_seconds: float = Field(default=0.0, description="Cumulative latency spent exclusively in LLM inference")
    tool_latency_seconds: float = Field(
        default=0.0, description="Cumulative latency spent exclusively in external MCP tool calls"
    )
    estimated_cost_usd: float = Field(default=0.0, description="Estimated inference cost in USD")
    spans: list[SpanMetric] = Field(default_factory=list, description="Granular trace spans breakdown")
